FROM wodby/adminer:4-3.18.4

RUN mkdir -p /var/www/html/designs/hydra \
    && wget https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css -O /var/www/html/designs/hydra/adminer.css